<%@ page language="java" contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%><!DOCTYPE html>
<html>
<head>
<title>下注详情 - <%=com.yy.guess.util.Util.getConfigCom(application).getWebTitle()%></title>
<%@include file="/m/head-common.jsp"%>
</head>
<body><noscript><strong>請啟用JavaScript已继续。</strong><br><h5>iOS > 设置 > Safari浏览器 > 高级 > JavaScript</h5><h5>Chrome > 设置 > 网站设置 > JavaScript</h5></noscript><div id="app" class=""><!----> <!----> <!----> <div class="loading-bkg" style="display: none;"><div data-v-c96941ea="" class="loading"><svg data-v-c96941ea="" version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="40px" height="40px" viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve"><path data-v-c96941ea="" opacity="0.2" fill="#000" d="M20.201,5.169c-8.254,0-14.946,6.692-14.946,14.946c0,8.255,6.692,14.946,14.946,14.946
  s14.946-6.691,14.946-14.946C35.146,11.861,28.455,5.169,20.201,5.169z M20.201,31.749c-6.425,0-11.634-5.208-11.634-11.634
  c0-6.425,5.209-11.634,11.634-11.634c6.425,0,11.633,5.209,11.633,11.634C31.834,26.541,26.626,31.749,20.201,31.749z"></path> <path data-v-c96941ea="" fill="#000" d="M26.013,10.047l1.654-2.866c-2.198-1.272-4.743-2.012-7.466-2.012h0v3.312h0
  C22.32,8.481,24.301,9.057,26.013,10.047z" transform="rotate(223.509 20 20)"><animateTransform data-v-c96941ea="" attributeType="xml" attributeName="transform" type="rotate" from="0 20 20" to="360 20 20" dur="0.5s" repeatCount="indefinite"></animateTransform></path></svg></div></div> <nav data-v-1db5fc32="" class="app-header" style=""><ul data-v-1db5fc32=""><li data-v-1db5fc32="" class="base-icon history-back"></li> <li data-v-1db5fc32="">游戏竞猜</li> <li data-v-1db5fc32="" class="base-icon"></li></ul></nav> <div class="weui-tab"> <div id="vux_view_box_body" class="weui-tab__panel vux-fix-safari-overflow-scrolling"><div data-v-31296f00="" class="betting-page router-view"><section data-v-31296f00="" class="betting-info"><section data-v-31296f00="" class="info-title"><img data-v-31296f00="" src="//yuanjududu.com//file/d511f1c87538e99ca914ef559dfa68ba.svg" width="20px"> <div data-v-31296f00="" class="tournament-name">ESL ANZ Championship</div> <div data-v-31296f00="" class="match-round">&nbsp;/ bo1</div></section> <section data-v-31296f00="" class="info-team"><div data-v-31296f00="" class="team-info"><img data-v-31296f00="" src="//yuanjududu.com//file/1672db3ae01e54f06cce4dc44ec6ec7a.png" class="team-logo"> <div data-v-31296f00="" class="team-name">Athletico Esport</div></div> <div data-v-31296f00="" class="betting-status"><div data-v-31296f00="" class="status-early"><div data-v-31296f00="" class="is-early"><div data-v-31296f00="" class="match-date">9月3日 周一</div> <div data-v-31296f00="" class="match-time">19:30</div></div></div> <div data-v-31296f00="" class="is-raedy">未开始</div> <!----> <!----></div> <div data-v-31296f00="" class="team-info"><img data-v-31296f00="" src="//yuanjududu.com//file/2c1bc68e92c4b9f12feb1fe0095bfef1.png" class="team-logo"> <div data-v-31296f00="" class="team-name">SaveBuyBackPlz</div></div></section></section> <!----> <section data-v-31296f00="" class="betting-stage"><div data-v-31296f00="" class="vux-tab-wrap"><div class="vux-tab-container"><div class="vux-tab"><div data-v-31296f00="" class="vux-tab-item vux-tab-selected" style="border: none; color: rgb(255, 255, 255);">全场
       <!----></div><div data-v-31296f00="" class="vux-tab-item" style="border: none; color: rgb(186, 206, 241);">地图1
       <!----></div> <div data-v-31296f00="" class="vux-tab-item vux-tab-disabled" style="border: none;">&nbsp;
         <!----></div><div data-v-31296f00="" class="vux-tab-item vux-tab-disabled" style="border: none;">&nbsp;
         <!----></div><div data-v-31296f00="" class="vux-tab-item vux-tab-disabled" style="border: none;">&nbsp;
         <!----></div> <div class="vux-tab-ink-bar vux-tab-ink-bar-transition-backward" style="display: block; height: 22px; background-color: transparent; left: 0%; right: 80%;"><!----></div></div></div></div></section> <section data-v-31296f00="" class="betting-odds"><div data-v-31296f00="" class="stage-title"><div data-v-31296f00="" class="stage-border"></div>
      全场
      <div data-v-31296f00="" class="stage-border"></div></div> <div data-v-31296f00="" class="group-list"><div data-v-8d7d541a="" data-v-31296f00="" class="odds-group-title odds-group-title"><div data-v-8d7d541a="" class="empty-badge">&nbsp;</div> <div data-v-8d7d541a="" class="title">获胜者</div></div> <div data-v-31296f00="" class="group-odds"><div data-v-31296f00="" class="odds-btn"><div data-v-549598f5="" data-v-31296f00="" class="home-match-card-button btn-selected"><div data-v-549598f5="" class="button-dark-border"><div data-v-549598f5="" class="button-content btn-left"><div data-v-549598f5="" class="button-name">Athletico Esport</div> <div data-v-549598f5="" class="button-odds-content"><div data-v-549598f5="" class="odds-rising-icon"></div> <div data-v-549598f5="" class="odds-dropping-icon"></div> <div data-v-549598f5="" class="btn-odds"><span data-v-549598f5="">1.27</span></div></div> <!----></div></div></div></div><div data-v-31296f00="" class="odds-btn"><div data-v-549598f5="" data-v-31296f00="" class="home-match-card-button"><div data-v-549598f5="" class="button-dark-border"><div data-v-549598f5="" class="button-content btn-right"><div data-v-549598f5="" class="button-odds-content"><div data-v-549598f5="" class="btn-odds"><span data-v-549598f5="">3.36</span></div> <div data-v-549598f5="" class="odds-rising-icon"></div> <div data-v-549598f5="" class="odds-dropping-icon"></div></div> <!----> <div data-v-549598f5="" class="button-name">SaveBuyBackPlz</div></div></div></div></div></div></div></section><section data-v-31296f00="" class="betting-odds"><div data-v-31296f00="" class="stage-title"><div data-v-31296f00="" class="stage-border"></div>
      地图1
      <div data-v-31296f00="" class="stage-border"></div></div> <div data-v-31296f00="" class="group-list"><div data-v-8d7d541a="" data-v-31296f00="" class="odds-group-title odds-group-title"><div data-v-8d7d541a="" class="empty-badge">&nbsp;</div> <div data-v-8d7d541a="" class="title">杀敌总数单双</div></div> <div data-v-31296f00="" class="group-odds"><div data-v-31296f00="" class="odds-btn"><div data-v-549598f5="" data-v-31296f00="" class="home-match-card-button"><div data-v-549598f5="" class="button-dark-border"><div data-v-549598f5="" class="button-content btn-left"><div data-v-549598f5="" class="button-name">比分为单</div> <div data-v-549598f5="" class="button-odds-content"><div data-v-549598f5="" class="odds-rising-icon"></div> <div data-v-549598f5="" class="odds-dropping-icon"></div> <div data-v-549598f5="" class="btn-odds"><span data-v-549598f5="">1.90</span></div></div> <!----></div></div></div></div><div data-v-31296f00="" class="odds-btn"><div data-v-549598f5="" data-v-31296f00="" class="home-match-card-button"><div data-v-549598f5="" class="button-dark-border"><div data-v-549598f5="" class="button-content btn-right"><div data-v-549598f5="" class="button-odds-content"><div data-v-549598f5="" class="btn-odds"><span data-v-549598f5="">1.90</span></div> <div data-v-549598f5="" class="odds-rising-icon"></div> <div data-v-549598f5="" class="odds-dropping-icon"></div></div> <!----> <div data-v-549598f5="" class="button-name">比分为双</div></div></div></div></div></div></div></section> <div data-v-31296f00="" style="height: 503px;"></div></div></div> </div> <div data-v-60a57f0c=""><div data-v-60a57f0c="" class="vux-popup-dialog bet-slip-pop vux-popup-bottom vux-popup-show vux-popup-dialog-er7xd" style="height: auto;"><section data-v-60a57f0c="" class="bet-slip-pop-header"><div data-v-60a57f0c="" class="slip-number">1</div> <div data-v-60a57f0c="" class="remove-all">删除全部
      </div> <div data-v-60a57f0c="" class="pop-header-text"><div data-v-60a57f0c="" class="pop-header-balance">余额</div> <div data-v-60a57f0c="">38.00</div></div> <div data-v-60a57f0c="" class="pop-header-close"></div></section> <section data-v-60a57f0c="" class="bet-slip-pop-body"><div data-v-60a57f0c="" class="pop-scroll" id="vux-scroller-mlz20" style="touch-action: auto; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative; overflow: hidden;"><div class="xs-container" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) translateZ(0px);"><div data-v-60a57f0c="" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(1) translateZ(0px);"><div data-v-60a57f0c="" class="vux-checker-box odds-list"><div data-v-60a57f0c=""><div data-v-60a57f0c="" class="vux-checker-item odds-item vux-tap-active"><div data-v-60a57f0c="" class="odds-list-line"></div> <section data-v-60a57f0c="" class="remove-odds"><div data-v-60a57f0c="" class="remove-odds-icon"></div></section> <section data-v-60a57f0c="" class="odds-item-match"><div data-v-60a57f0c="" class="odds-name">Athletico Esport</div> <div data-v-60a57f0c="">全场 获胜者</div> <div data-v-60a57f0c="">Athletico Esport - VS - SaveBuyBackPlz</div></section> <section data-v-60a57f0c="" class="odds-item-money"><div data-v-60a57f0c="" class="item-money"><div data-v-60a57f0c="" class="money-odds">@1.27
                    </div> <div data-v-60a57f0c="" class="stake-input stake-input-focus"><span data-v-60a57f0c="" class="input-text">10
                      </span></div></div> <div data-v-60a57f0c="" class="item-return">
                    预计还返
                    <span data-v-60a57f0c="" class="return-amount">12.7</span></div></section></div> <div data-v-90afda32="" data-v-60a57f0c="" class="base-Keyboard single-keyboard"><div data-v-90afda32="" class="content"><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">1</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">2</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">3</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">4</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">5</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">6</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">7</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">8</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">9</div></div><div data-v-90afda32="" class="content-number"><div data-v-90afda32="">0</div></div></div> <div data-v-90afda32="" class="content"><div data-v-90afda32="" class="max-btn"><div data-v-90afda32="">最大投注</div> <!----></div> <div data-v-90afda32="" class="del-btn"><div data-v-90afda32="" class="del-icon"></div></div> <div data-v-90afda32="" class="confirm-btn"><div data-v-90afda32="">确认</div></div></div></div></div></div> <!----></div>  </div><div class=" xs-fixed-container"></div></div></section> <!----></div> <section data-v-60a57f0c="" class="bet-slip-tab"><div data-v-60a57f0c="" class="tab-content"><div data-v-60a57f0c="" class="content-left"><div data-v-60a57f0c="" class="bet-amount"><div data-v-60a57f0c="">投注金额
            <span data-v-60a57f0c="">10.00</span></div> <div data-v-60a57f0c="" style="height: 2px;"></div> <div data-v-60a57f0c="">最高还返
            <span data-v-60a57f0c="" class="total-return">12.70</span></div></div> <div data-v-60a57f0c="" class="toggle-tab">收起
        </div></div> <div data-v-60a57f0c="" class="bet-btn submitting-btn">正在下单
      </div></div></section> <!----> <div data-v-60a57f0c="" class="vux-confirm order-confirm"><div class="vux-x-dialog"><div class="weui-mask" style=""></div> <div class="weui-dialog" style=""><!----> <div class="weui-dialog__bd"><div class="content"><section class="header color-green"><div class="success-icon"></div> <div>订单提交成功！</div></section> <div id="vux-scroller-tds6q" style="max-height: 60vh; height: 186px; touch-action: auto; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative; overflow: hidden;"><div class="xs-container" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) translateZ(0px);"><div style="height: 186px; transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(1) translateZ(0px);"><div class="order-item"><div class="odds-item"><div class="match-info"><div class="odds-title"><div class="games-icon" style="background-image: url(&quot;//yuanjududu.com//file/d511f1c87538e99ca914ef559dfa68ba.svg&quot;);"></div>
                Athletico Esport
                <div class="match-stage">全场 赛前</div></div> <div class="odds-match">Athletico Esport - VS - SaveBuyBackPlz 19:00</div> <div>赔率: 1.27</div></div></div> <div class="order-info order-title"><div>单场</div> <div class="order-success">提交成功</div></div> <div class="order-info"><div class="stake">投注金额:
              <span class="color-white">10</span></div> <div>盈利:
              <span class="color-white">
                12.7
              </span></div></div> <div class="order-note">您的订单需要系统确认，请在“投注记录”留意订单状态</div></div></div>  </div><div class=" xs-fixed-container"></div></div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_default">投注记录</a> <a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">继续投注</a></div></div></div></div></div> <!----></div><script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-115025704-1"></script><script>window.dataLayer = window.dataLayer || []

    function gtag() {
      dataLayer.push(arguments)
    }
    gtag('js', new Date())

    gtag('config', 'UA-115025704-1')
    window.addEventListener('load', function () {
      setTimeout(function () {
        window.scrollTo(0, 1)
      }, 10)
    })</script><script type="text/javascript" src="static/js/manifest.569709e9b6416c4decb5.js"></script><script type="text/javascript" src="static/js/vendor.a457f24991fca5f2ac72.js"></script><script type="text/javascript" src="static/js/app.025d194ca9a0fd517ef4.js"></script><div class="vux-alert"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><div class="weui-dialog__hd"><strong class="weui-dialog__title"></strong></div> <div class="weui-dialog__bd"><div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">确定</a></div></div></div></div><div class="vux-confirm"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><!----> <div class="weui-dialog__bd"><div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_default">取消</a> <a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">确定</a></div></div></div></div><div class="vux-toast"><div class="weui-mask_transparent" style="display: none;"></div> <div class="weui-toast weui-toast_text vux-toast-middle" style="width: 80%; display: none;"><i class="weui-icon-success-no-circle weui-icon_toast" style="display: none;"></i> <p class="weui-toast__content">最小投注金额 10</p></div></div><div data-v-cd2dfd02="" class="base-alert v-transfer-dom"><div data-v-cd2dfd02="" class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="background: transparent; display: none;"><div data-v-cd2dfd02="" class="alert-content"><div data-v-cd2dfd02="" class="warning"></div> <div data-v-cd2dfd02="" class="alert-text"></div> <div data-v-cd2dfd02="" class="alert-hr"></div> <div data-v-cd2dfd02="" class="alert-btn">确认
      </div></div></div></div></div><a class="vux-popup-mask" data-uuid=",3z4ow,nxa0k,er7xd" href="javascript:void(0)" style="z-index: -1;"></a><div data-v-60a57f0c="" class="base-confirm v-transfer-dom"><div class="vux-confirm"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><!----> <div class="weui-dialog__bd"><div class="content warning-content"><div class="warning"></div> <div>抱歉，您的帐户余额不足，请先存款</div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_default">先看看</a> <a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">去存款</a></div></div></div></div></div></body>
</html>