<%@ page language="java" contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%><!DOCTYPE html>
<html>
<head>
<title> - <%=com.yy.guess.util.Util.getConfigCom(application).getWebTitle()%></title>
<%@include file="/m/head-common.jsp"%>
</head>
<body><noscript><strong>請啟用JavaScript已继续。</strong><br><h5>iOS > 设置 > Safari浏览器 > 高级 > JavaScript</h5><h5>Chrome > 设置 > 网站设置 > JavaScript</h5></noscript><div id="app" class="no-pb"><!----> <!----> <!----> <div class="loading-bkg" style="display: none;"><div data-v-c96941ea="" class="loading"><svg data-v-c96941ea="" version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="40px" height="40px" viewBox="0 0 40 40" enable-background="new 0 0 40 40" xml:space="preserve"><path data-v-c96941ea="" opacity="0.2" fill="#000" d="M20.201,5.169c-8.254,0-14.946,6.692-14.946,14.946c0,8.255,6.692,14.946,14.946,14.946
  s14.946-6.691,14.946-14.946C35.146,11.861,28.455,5.169,20.201,5.169z M20.201,31.749c-6.425,0-11.634-5.208-11.634-11.634
  c0-6.425,5.209-11.634,11.634-11.634c6.425,0,11.633,5.209,11.633,11.634C31.834,26.541,26.626,31.749,20.201,31.749z"></path> <path data-v-c96941ea="" fill="#000" d="M26.013,10.047l1.654-2.866c-2.198-1.272-4.743-2.012-7.466-2.012h0v3.312h0
  C22.32,8.481,24.301,9.057,26.013,10.047z" transform="rotate(295.012 20 20)"><animateTransform data-v-c96941ea="" attributeType="xml" attributeName="transform" type="rotate" from="0 20 20" to="360 20 20" dur="0.5s" repeatCount="indefinite"></animateTransform></path></svg></div></div> <nav data-v-1db5fc32="" class="app-header agent-header" style="display: none;"><ul data-v-1db5fc32=""><li data-v-1db5fc32="" class="base-icon history-back"></li> <li data-v-1db5fc32="">个人资料</li> <li data-v-1db5fc32="" class="base-icon"></li></ul></nav> <div class="weui-tab trans-view"> <div id="vux_view_box_body" class="weui-tab__panel vux-fix-safari-overflow-scrolling"><div data-v-7478f51e="" class="agent-page router-view"><section data-v-7478f51e="" class="agent-header"><a data-v-7478f51e="" href="#/personal" class="base-icon history-back router-link-active"></a> <a data-v-e7bb725a="" data-v-7478f51e="" href="//www.xlbmama.com/chat/h5/index.html?sysNum=322d704743e04896b8a70524ae45127e" target="_blank" rel="noopener noreferrer" class="customer-service base-icon service-link">
  
  </a></section> <div data-v-7478f51e="" id="vux-scroller-3oocy" style="height: 887px; touch-action: auto; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative; overflow: hidden;"><div class="xs-container" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) translateZ(0px);"><div data-v-7478f51e="" class="vux-slider" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(1) translateZ(0px);"><div class="vux-swiper" style="height: 887px;"><div data-v-7478f51e="" class="vux-swiper-item" style="transform: translate3d(0px, -887px, 0px); transition: all 300ms ease 0s;"><img data-v-7478f51e="" src="static/img/intro4.f3e9e9f.png" width="100%"></div> <div data-v-7478f51e="" class="vux-swiper-item intro-bkg" style="transform: translate3d(0px, 0px, 0px); transition: all 300ms ease 0s;"><div data-v-7478f51e="" class="intro-content"><div data-v-7478f51e="" class="title">结算最快</div> <div data-v-7478f51e="">和黑钱说
            <span data-v-7478f51e="" class="slogan">NO</span></div> <div data-v-7478f51e="" class="text">数据准确，每月2号自动结算，资金安全便捷</div></div> <img data-v-7478f51e="" src="static/img/intro1.8745b80.png" width="100%"></div> <div data-v-7478f51e="" class="vux-swiper-item intro-bkg" style="transform: translate3d(0px, 887px, 0px); transition: all 300ms ease 0s;"><div data-v-7478f51e="" class="intro-content"><div data-v-7478f51e="" class="title">最高分紅</div> <div data-v-7478f51e="">和45%说
            <span data-v-7478f51e="" class="slogan">NO</span></div> <div data-v-7478f51e="" class="text">最高代理分红比例52%，同比业界高7个点</div></div> <img data-v-7478f51e="" src="static/img/intro2.3aa0f76.png" width="100%"></div> <div data-v-7478f51e="" class="vux-swiper-item intro-bkg" style="transform: translate3d(0px, 1774px, 0px); transition: all 300ms ease 0s;"><div data-v-7478f51e="" class="intro-content"><div data-v-7478f51e="" class="title">专业电竞</div> <div data-v-7478f51e="">和小公司说
            <span data-v-7478f51e="" class="slogan">NO</span></div> <div data-v-7478f51e="" class="text">欧洲牌照，newbee赞助商</div></div> <img data-v-7478f51e="" src="static/img/intro3.a1e50d6.png" width="100%"></div>  </div> <div class="vux-indicator vux-indicator-right" style="display: none;"><a href="javascript:"><i class="vux-icon-dot"></i></a><a href="javascript:"><i class="vux-icon-dot active"></i></a><a href="javascript:"><i class="vux-icon-dot"></i></a><a href="javascript:"><i class="vux-icon-dot"></i></a></div></div>  </div><div class=" xs-fixed-container"></div></div> <section data-v-7478f51e="" class="agent-button"><div data-v-0f69c571="" data-v-7478f51e="" class="base-button"><div data-v-0f69c571="" class="button-border"><button data-v-0f69c571="" type="submit" class="button-content">
      成为代理
    </button></div></div></section> <div data-v-7478f51e="" class="to-agent-content">了解代理合营内容
  </div> <div data-v-7478f51e="" class="arrow-next"></div></div></div> </div> <div data-v-60a57f0c="" style="display: none;"><div data-v-60a57f0c="" class="vux-popup-dialog bet-slip-pop vux-popup-bottom vux-popup-show" style="height: auto;"><section data-v-60a57f0c="" class="bet-slip-pop-header"><div data-v-60a57f0c="" class="slip-number">2</div> <div data-v-60a57f0c="" class="remove-all">删除全部
      </div> <div data-v-60a57f0c="" class="pop-header-text"><div data-v-60a57f0c="" class="pop-header-balance">余额</div> <div data-v-60a57f0c="">0.00</div></div> <div data-v-60a57f0c="" class="pop-header-close"></div></section> <section data-v-60a57f0c="" class="bet-slip-pop-body"><div data-v-60a57f0c="" class="pop-scroll" id="vux-scroller-t0et1" style="touch-action: auto; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative; overflow: hidden;"><div class="xs-container" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) translateZ(0px);"><div data-v-60a57f0c="" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(1) translateZ(0px);"><div data-v-60a57f0c="" class="vux-checker-box odds-list"><div data-v-60a57f0c=""><div data-v-60a57f0c="" class="vux-checker-item odds-item vux-tap-active"><div data-v-60a57f0c="" class="odds-list-line"></div> <section data-v-60a57f0c="" class="remove-odds"><div data-v-60a57f0c="" class="remove-odds-icon"></div></section> <section data-v-60a57f0c="" class="odds-item-match"><div data-v-60a57f0c="" class="odds-name">Athletico Esport</div> <div data-v-60a57f0c="">全场 获胜者</div> <div data-v-60a57f0c="">Athletico Esport - VS - SaveBuyBackPlz</div></section> <section data-v-60a57f0c="" class="odds-item-money"><div data-v-60a57f0c="" class="item-money"><div data-v-60a57f0c="" class="money-odds">@1.23
                    </div> <div data-v-60a57f0c="" class="stake-input"><span data-v-60a57f0c="" class="input-placeholder">输入金额
                      </span></div></div> <div data-v-60a57f0c="" class="item-return">
                    预计还返
                    <span data-v-60a57f0c="" class="return-amount">0</span></div></section></div> <!----></div><div data-v-60a57f0c=""><div data-v-60a57f0c="" class="vux-checker-item odds-item vux-tap-active"><div data-v-60a57f0c="" class="odds-list-line"></div> <section data-v-60a57f0c="" class="remove-odds"><div data-v-60a57f0c="" class="remove-odds-icon"></div></section> <section data-v-60a57f0c="" class="odds-item-match"><div data-v-60a57f0c="" class="odds-name">NB.Y</div> <div data-v-60a57f0c="">地图1 获胜者</div> <div data-v-60a57f0c="">NB.Y - VS - Avalon</div></section> <section data-v-60a57f0c="" class="odds-item-money"><div data-v-60a57f0c="" class="item-money"><div data-v-60a57f0c="" class="money-odds">@1.35
                    </div> <div data-v-60a57f0c="" class="stake-input"><span data-v-60a57f0c="" class="input-placeholder">输入金额
                      </span></div></div> <div data-v-60a57f0c="" class="item-return">
                    预计还返
                    <span data-v-60a57f0c="" class="return-amount">0</span></div></section></div> <!----></div></div> <div data-v-60a57f0c="" class="show-all-multiples"><span data-v-60a57f0c="">过关选项</span> <div data-v-60a57f0c="" class="hide-parlay-icon"></div></div> <div data-v-60a57f0c="" class="vux-checker-box odds-list"><div data-v-60a57f0c="" style="display: none;"><div data-v-60a57f0c="" class="vux-checker-item parlay-item vux-tap-active"><!----> <div data-v-60a57f0c="" class="parlay-item-info"><div data-v-60a57f0c="" class="parlay-title">单场</div> <div data-v-60a57f0c="" class="item-return">预计还返
                      <span data-v-60a57f0c="" class="return-amount">0</span></div></div> <div data-v-60a57f0c="" class="parlay-item-money"><!----> <div data-v-60a57f0c="" class="parlay-number">2</div> <div data-v-60a57f0c="" class="parlay-cross">&nbsp;×</div> <div data-v-60a57f0c="" class="stake-input"><span data-v-60a57f0c="" class="input-placeholder">输入金额
                      </span></div></div></div> <!----></div><div data-v-60a57f0c=""><div data-v-60a57f0c="" class="vux-checker-item parlay-item vux-tap-active"><!----> <div data-v-60a57f0c="" class="parlay-item-info"><div data-v-60a57f0c="" class="parlay-title">2串1</div> <div data-v-60a57f0c="" class="item-return">预计还返
                      <span data-v-60a57f0c="" class="return-amount">0</span></div></div> <div data-v-60a57f0c="" class="parlay-item-money"><div data-v-60a57f0c="" class="money-odds">@1.63
                    </div> <div data-v-60a57f0c="" class="parlay-number">1</div> <div data-v-60a57f0c="" class="parlay-cross">&nbsp;×</div> <div data-v-60a57f0c="" class="stake-input"><span data-v-60a57f0c="" class="input-placeholder">输入金额
                      </span></div></div></div> <!----></div></div></div>  </div><div class=" xs-fixed-container"></div></div></section> <!----></div> <section data-v-60a57f0c="" class="bet-slip-tab"><div data-v-60a57f0c="" class="tab-content"><div data-v-60a57f0c="" class="content-left"><div data-v-60a57f0c="" class="bet-amount"><div data-v-60a57f0c="">投注金额
            <span data-v-60a57f0c="">0.00</span></div> <div data-v-60a57f0c="" style="height: 2px;"></div> <div data-v-60a57f0c="">最高还返
            <span data-v-60a57f0c="" class="total-return">0.00</span></div></div> <div data-v-60a57f0c="" class="toggle-tab">收起
        </div></div> <div data-v-60a57f0c="" class="bet-btn">
        确认投注
      </div></div></section> <!----> <div data-v-60a57f0c="" class="vux-confirm order-confirm"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><!----> <div class="weui-dialog__bd"><div class="content"><section class="header color-green"><div class="success-icon"></div> <div>订单提交成功！</div></section> <div id="vux-scroller-ea7md" style="max-height: 60vh; height: 0px; touch-action: auto; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative; overflow: hidden;"><div class="xs-container" style="transform-origin: 0px 0px 0px; transform: translate(0px, 0px) translateZ(0px);"><div style="height: 0px; transform-origin: 0px 0px 0px; transform: translate(0px, 0px) scale(1) translateZ(0px);"></div>  </div><div class=" xs-fixed-container"></div></div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_default">投注记录</a> <a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">继续投注</a></div></div></div></div></div> <div data-v-4e9bdfde="" class="apply-agent"><div data-v-4e9bdfde="" class="apply-card"><section data-v-4e9bdfde="" class="card-title"><div data-v-4e9bdfde="" class="base-icon">&nbsp;</div> <div data-v-4e9bdfde="">成为代理</div> <div data-v-4e9bdfde="" class="base-icon close-icon"></div></section> <form data-v-4e9bdfde="" onsubmit="return false"><div data-v-0fdb235f="" data-v-4e9bdfde="" class="base-input light-border" click="return false"><input data-v-0fdb235f="" id="用户名" type="text" placeholder="" readonly="readonly" autocomplete="off" autocorrect="off" autocapitalize="off"> <label data-v-0fdb235f="" for="用户名" class="input-label">用户名
  </label> <span data-v-0fdb235f="" class="focus-border"></span> <!---->  <!----></div> <div data-v-0fdb235f="" data-v-4e9bdfde="" class="base-input light-border"><input data-v-0fdb235f="" id="QQ" type="text" placeholder="请输入QQ帐号" autocomplete="off" autocorrect="off" autocapitalize="off"> <label data-v-0fdb235f="" for="QQ" class="input-label">QQ
  </label> <span data-v-0fdb235f="" class="focus-border"></span> <!---->  <!----></div> <div data-v-0fdb235f="" data-v-4e9bdfde="" class="base-input light-border"><input data-v-0fdb235f="" id="个人网站" type="text" placeholder="无网址可不必填" autocomplete="off" autocorrect="off" autocapitalize="off"> <label data-v-0fdb235f="" for="个人网站" class="input-label">个人网站
  </label> <span data-v-0fdb235f="" class="focus-border"></span> <!---->  <!----></div> <div data-v-cca08c2a="" data-v-4e9bdfde="" class="base-textarea light-border"><textarea data-v-cca08c2a="" id="推广介绍" type="text" placeholder="请说明如何推广" autocomplete="off" autocorrect="off" autocapitalize="off"></textarea> <label data-v-cca08c2a="" for="推广介绍" class="input-label">推广介绍
  </label> <span data-v-cca08c2a="" class="focus-border"></span> <!---->  <!----></div> <div data-v-4e9bdfde="" style="height: 26px;"></div> <div data-v-0f69c571="" data-v-4e9bdfde="" class="base-button base-button-disabled"><div data-v-0f69c571="" class="button-border"><button data-v-0f69c571="" type="submit" class="button-content">
      确认
    </button></div></div></form></div></div></div><script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-115025704-1"></script><script>window.dataLayer = window.dataLayer || []

    function gtag() {
      dataLayer.push(arguments)
    }
    gtag('js', new Date())

    gtag('config', 'UA-115025704-1')
    window.addEventListener('load', function () {
      setTimeout(function () {
        window.scrollTo(0, 1)
      }, 10)
    })</script><script type="text/javascript" src="static/js/manifest.569709e9b6416c4decb5.js"></script><script type="text/javascript" src="static/js/vendor.a457f24991fca5f2ac72.js"></script><script type="text/javascript" src="static/js/app.025d194ca9a0fd517ef4.js"></script><div class="vux-alert"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><div class="weui-dialog__hd"><strong class="weui-dialog__title"></strong></div> <div class="weui-dialog__bd"><div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">确定</a></div></div></div></div><div class="vux-confirm"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><!----> <div class="weui-dialog__bd"><div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_default">取消</a> <a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">确定</a></div></div></div></div><div class="vux-toast"><div class="weui-mask_transparent" style="display: none;"></div> <div class="weui-toast weui-toast_success vux-toast-middle" style="width: 7.6em; display: none;"><i class="weui-icon-success-no-circle weui-icon_toast" style=""></i> <p class="weui-toast__content">登录成功</p></div></div><div data-v-cd2dfd02="" class="base-alert v-transfer-dom"><div data-v-cd2dfd02="" class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="background: transparent; display: none;"><div data-v-cd2dfd02="" class="alert-content"><div data-v-cd2dfd02="" class="warning"></div> <div data-v-cd2dfd02="" class="alert-text"></div> <div data-v-cd2dfd02="" class="alert-hr"></div> <div data-v-cd2dfd02="" class="alert-btn">确认
      </div></div></div></div></div><a class="vux-popup-mask" data-uuid=",3z4ow,nxa0k,6mqsl" href="javascript:void(0)" style="z-index: -1;"></a><div data-v-60a57f0c="" class="base-confirm v-transfer-dom"><div class="vux-confirm"><div class="vux-x-dialog"><div class="weui-mask" style="display: none;"></div> <div class="weui-dialog" style="display: none;"><!----> <div class="weui-dialog__bd"><div class="content warning-content"><div class="warning"></div> <div>抱歉，您的帐户余额不足，请先存款</div></div></div> <div class="weui-dialog__ft"><a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_default">先看看</a> <a href="javascript:;" class="weui-dialog__btn weui-dialog__btn_primary">去存款</a></div></div></div></div></div></body>
</html>